_target_: src.model.grind.GrIND
input_dim: 1
spatial_dim: 2
max_order: 2
accuracy: 1
symnet_hidden_size: 128
symnet_hidden_layers: 3
num_ks: 21
grid_resolution: 64
use_smoother: False
use_adjoint: True
use_instance_norm: True
solver:
  method: 'euler'
  options:
    step_size: 0.01
learning_rate: 0.001
weight_decay: 0.0
training_noise: 0.0