_target_: src.model.grind.GrIND
input_dim: 1
spatial_dim: 2
max_order: 4
accuracy: 1
symnet_hidden_size: 128
symnet_hidden_layers: 3
num_ks: 21
grid_resolution: 64
solver:
  method: 'euler'
  options:
    step_size: 0.05
learning_rate: 0.001