_target_: pytorch_lightning.Trainer
max_epochs: 10
limit_train_batches: 10000
limit_val_batches: 100
limit_test_batches: 1000
gradient_clip_val: 0.5

accelerator: gpu
devices: 1
callbacks:
  - _target_: pytorch_lightning.callbacks.ModelCheckpoint
    save_last: True
logger:
  - _target_: pytorch_lightning.loggers.TensorBoardLogger
    save_dir: ./output/tb_logs
    version: ${experiment_name}
  - _target_: pytorch_lightning.loggers.wandb.WandbLogger
    name: ${experiment_name}
    offline: False
    project: grind
    entity: magnet4cardiac7t
    save_dir: ./output