_target_: torch.utils.data.DataLoader
dataset:
  _target_: src.dataset.interpolation.DynabenchInterpolator
  split: train
  equation: kuramotosivashinsky
  resolution: high
  base_path: data
batch_size: 16
num_workers: 16