defaults:
  - datamodule: default
  - model: grind_neuralpde
  - trainer: default

experiment_name: interpolation-test
project_name: grind-neuralpde-final
logging_suffix: ""

train_from_checkpoint: last
test_from_checkpoint: best

train: True
test: True

hydra:
  run:
    dir: output/hydra/${experiment_name}/${now:%Y-%m-%d_%H-%M-%S}