defaults:
  - datamodule: default
  - model: grind_neuralpde
  - trainer: default

experiment_name: test
project_name: grind-neuralpde
logging_suffix: ""

train_from_checkpoint: last
test_from_checkpoint: best
  

hydra:
  run:
    dir: output/hydra/${experiment_name}/${now:%Y-%m-%d_%H-%M-%S}